[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
#dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
#dependencies = ["clean"]

[tasks.simple]
dependencies = [
    "format",
    "build",
    "test"
]
