binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "PreferSameLine"
comment_width = 80
control_brace_style = "AlwaysSameLine"
wrap_comments = true
edition = "2018"
empty_item_single_line = true
error_on_line_overflow = true
error_on_unformatted = true
fn_single_line = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
hard_tabs = false
match_arm_blocks = false
match_block_trailing_comma = true
max_width = 80
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
report_fixme = "Always"
report_todo = "Always"
tab_spaces = 2
use_try_shorthand = true
